import Header from '@/app/Header';
import './globals.css';
import { Playfair_Display } from 'next/font/google';
import Footer from './Footer';

const playfair = Playfair_Display({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={playfair.className}>
        <main className=''>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
